export const GET_VEHICLES_ADVANCED_SEARCH = "GET_VEHICLES_ADVANCED_SEARCH";
export const GET_PREOWNEDS_ADVANCED_SEARCH = "GET_PREOWNEDS_ADVANCED_SEARCH";
export const GET_JOBS_ADVANCED_SEARCH = "GET_JOBS_ADVANCED_SEARCH";
export const CLEAR_STATE = "CLEAR_STATE";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_MAKES = "GET_MAKES";

// Jobs
export const SET_JOB = 'SET_JOB';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Applicant
export const CREATE_APPLICANT = 'CREATE_APPLICANT';

// Medias
export const GET_MEDIAS_MAIN_BANNER = 'GET_MEDIAS_MAIN_BANNER';

// Stores
export const GET_STORES = 'GET_STORES';