export const GET_VEHICLES_ADVANCED_SEARCH = "GET_VEHICLES_ADVANCED_SEARCH";
export const GET_JOBS_ADVANCED_SEARCH = "GET_JOBS_ADVANCED_SEARCH";
export const CLEAR_STATE = "CLEAR_STATE";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_MAKES = "GET_MAKES";